FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir temp_uploads && chmod 77 temp_uploads

COPY
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]